run:
  deadline: 1m
  tests: true

  skip-dirs-use-default: true

linters-settings:
  errcheck:
    check-blank: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 200
  nakedret:
    max-func-lines: 50
  funlen:
    lines: 80
    statements: 50

linters:
  disable-all: true
  enable:
    # enabled by default (according to https://golangci-lint.run/usage/linters/):
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused

    # disabled by default
    - bodyclose
    - dupl
    - copyloopvar
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - misspell
    - nakedret
    - prealloc
    - revive
    - stylecheck
    - unconvert
    - unparam
  fast: false

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files: '.*\.test\.go|.*\.pb\.go'
  exclude:
    - "should have comment"
    - "always receives"
    - "parameter .* is always"
    - "comment on exported .* should be of the form"

output:
  formats: colored-line-number
